INSERT INTO CivilizationCitizenNames
       (CivilizationType,   CitizenName)
VALUES ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_1'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_2'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_3'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_4'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_5'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_6'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_7'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_8'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_9'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_MALE_10');

INSERT INTO CivilizationCitizenNames
       (CivilizationType,   CitizenName, Female)
VALUES ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_1', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_2', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_3', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_4', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_5', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_6', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_7', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_8', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_9', 'true'),
       ('CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CITIZEN_NYGUITA_ARGENTINA_FEMALE_10', 'true');
