UPDATE Civilizations SET UniqueCultureProgressionTree="TREE_CIVICS_EX_TEST_OF_TIME" WHERE CivilizationType="CIVILIZATION_NYGUITA_ARGENTINA";

INSERT INTO CivilizationTraits
        (CivilizationType,  TraitType)
VALUES  ("CIVILIZATION_NYGUITA_ARGENTINA",  "TRAIT_ANACHRONISTIC_CIV");

DELETE FROM TraitModifiers WHERE TraitType = "TRAIT_NYGUITA_ARGENTINA_ABILITY";

INSERT INTO TraitModifiers 
       (TraitType,                         ModifierId) 
VALUES ('TRAIT_NYGUITA_ARGENTINA_ABILITY', 'TRAIT_MOD_NYGUITA_ARGENTINA_PATAGONIAN_LAND_RUSH_RESOURCE_FOOD'),
       ('TRAIT_NYGUITA_ARGENTINA_ABILITY', 'TRAIT_MOD_NYGUITA_ARGENTINA_PATAGONIAN_LAND_RUSH_RESOURCE_PRODUCTION'),
       ('TRAIT_NYGUITA_ARGENTINA_ABILITY', 'TRAIT_MOD_NYGUITA_ARGENTINA_PATAGONIAN_LAND_RUSH_RESOURCE_GOLD'),
       ('TRAIT_NYGUITA_ARGENTINA_ABILITY', 'TRAIT_MOD_NYGUITA_ARGENTINA_PATAGONIAN_LAND_RUSH_RESOURCE_CAP'),
       ('TRAIT_NYGUITA_ARGENTINA_ABILITY', 'TRAIT_MOD_NYGUITA_ARGENTINA_MIGRANT_WHEN_CELEBRATION_EX');
