INSERT INTO NamedRivers
       (NamedRiverType, Name)
VALUES ('URUGUAY_RIVER', 'LOC_NYGUITA_RIVER_URUGUAY_NAME'),
       ('BERMEJO_RIVER', 'LOC_NYGUITA_RIVER_BERMEJO_NAME'),
       ('PILCOMAYO_RIVER', 'LOC_NYGUITA_RIVER_PILCOMAYO_NAME');

INSERT INTO NamedVolcanoes
       (NamedVolcanoType, Name)
VALUES ('VOLCANO_LLULLAILLACO', 'LOC_NYGUITA_VOLCANO_LLULLAILLACO_NAME'),
       ('VOLCANO_CERRO_TIPAS', 'LOC_NYGUITA_VOLCANO_CERRO_TIPAS_NAME'),
       ('VOLCANO_INCAHUASI', 'LOC_NYGUITA_VOLCANO_INCAHUASI_NAME');

INSERT INTO NamedVolcanoCivilizations
       (NamedVolcanoType, CivilizationType)
VALUES ('VOLCANO_OJOS_DEL_SALADO', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('VOLCANO_LLULLAILLACO', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('VOLCANO_CERRO_TIPAS', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('VOLCANO_INCAHUASI', 'CIVILIZATION_NYGUITA_ARGENTINA');

INSERT INTO NamedRiverCivilizations
       (NamedRiverType, CivilizationType)
VALUES ('PARANA_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('URUGUAY_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('RIO_NEGRO', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('BERMEJO_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('PILCOMAYO_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('COLORADO_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('SALADO_RIVER', 'CIVILIZATION_NYGUITA_ARGENTINA');