INSERT INTO Civilizations 
       (Domain,                   CivilizationType,                 CivilizationName,                          CivilizationFullName,                           CivilizationDescription,                          CivilizationIcon) 
VALUES ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_FULL_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_DESCRIPTION', 'CIVILIZATION_NYGUITA_ARGENTINA');

INSERT INTO CivilizationTags 
       (CivilizationDomain,       CivilizationType,                 TagType) 
VALUES ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TAG_TRAIT_ECONOMIC'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TAG_TRAIT_EXPANSIONIST');

INSERT INTO CivilizationItems 
       (CivilizationDomain,       CivilizationType,                 Type,                              Kind,         Name,                                              Description,                                              Icon) 
VALUES ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TRAIT_NYGUITA_ARGENTINA_ABILITY', 'KIND_TRAIT', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_DESCRIPTION', 'CIVILIZATION_NYGUITA_ARGENTINA'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'UNIT_NYGUITA_GAUCHO', 'KIND_UNIT', 'LOC_UNIT_NYGUITA_GAUCHO_NAME', 'LOC_UNIT_NYGUITA_GAUCHO_BASE_DESCRIPTION', 'UNIT_NYGUITA_GAUCHO'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'UNIT_NYGUITA_PORTENO', 'KIND_UNIT', 'LOC_UNIT_NYGUITA_PORTENO_NAME', 'LOC_UNIT_NYGUITA_PORTENO_DESCRIPTION', 'UNIT_NYGUITA_PORTENO'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'QUARTER_NYGUITA_PLAZA_DE_MAYO', 'KIND_QUARTER', 'LOC_QUARTER_NYGUITA_PLAZA_DE_MAYO_NAME', 'LOC_QUARTER_NYGUITA_PLAZA_DE_MAYO_DESCRIPTION', 'QUARTER_NYGUITA_PLAZA_DE_MAYO'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'BUILDING_NYGUITA_BANCO_NACION', 'KIND_IMPROVEMENT', 'LOC_BUILDING_NYGUITA_BANCO_NACION_NAME', 'LOC_BUILDING_NYGUITA_BANCO_NACION_DESCRIPTION', 'BUILDING_NYGUITA_BANCO_NACION'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'BUILDING_NYGUITA_SALADERO', 'KIND_IMPROVEMENT', 'LOC_BUILDING_NYGUITA_SALADERO_NAME', 'LOC_BUILDING_NYGUITA_SALADERO_DESCRIPTION', 'BUILDING_NYGUITA_SALADERO');
