INSERT INTO Civilizations 
       (Domain,                   CivilizationType,                 CivilizationName,                          CivilizationFullName,                           CivilizationDescription,                          CivilizationIcon) 
VALUES ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_FULL_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_DESCRIPTION', 'CIVILIZATION_NYGUITA_ARGENTINA');

INSERT INTO CivilizationTags 
       (CivilizationDomain,       CivilizationType,                 TagType) 
VALUES ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TAG_TRAIT_ECONOMIC'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TAG_TRAIT_EXPANSIONIST'),
       ('ModernAgeCivilizations', 'CIVILIZATION_NYGUITA_ARGENTINA', 'TAG_APEX_AGE_MODERN');

INSERT INTO CivilizationItems 
       	(CivilizationDomain,        AgeType,				CivilizationType,    				Type,  							Kind,  			Name,  											Description)
VALUES 	('ModernAgeCivilizations', 'AGE_MODERN',			'CIVILIZATION_NYGUITA_ARGENTINA', 'TRAIT_NYGUITA_ARGENTINA_ABILITY', 'KIND_TRAIT', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_DESCRIPTION'),
		('ModernAgeCivilizations', 'AGE_MODERN',	              'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_CAUDILLISM_II', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_CAUDILLISM_II_NAME', 'LOC_TRADITION_NYGUITA_CAUDILLISM_II_DESCRIPTION'),
		('ModernAgeCivilizations', 'AGE_MODERN',	              'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_II', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_II_NAME', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_II_DESCRIPTION'),
		('ModernAgeCivilizations', 'AGE_MODERN',	              'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_NUEVO_TANGO', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_NUEVO_TANGO_NAME', 'LOC_TRADITION_NYGUITA_NUEVO_TANGO_DESCRIPTION'),
		('AntiquityAgeCivilizations', 'AGE_ANTIQUITY',		'CIVILIZATION_NYGUITA_ARGENTINA', 'TRAIT_NYGUITA_ARGENTINA_ABILITY', 'KIND_TRAIT', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_AQ_DESCRIPTION'),
		('AntiquityAgeCivilizations', 'AGE_ANTIQUITY',		'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_CAUDILLISM_I', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_CAUDILLISM_I_NAME', 'LOC_TRADITION_NYGUITA_CAUDILLISM_I_DESCRIPTION'),
		('AntiquityAgeCivilizations', 'AGE_ANTIQUITY',		'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_ANTIQUITY', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_ANTIQUITY_NAME', 'LOC_TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_ANTIQUITY_DESCRIPTION'),
		('ExplorationAgeCivilizations', 'AGE_EXPLORATION',	'CIVILIZATION_NYGUITA_ARGENTINA', 'TRAIT_NYGUITA_ARGENTINA_ABILITY', 'KIND_TRAIT', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_NAME', 'LOC_CIVILIZATION_NYGUITA_ARGENTINA_ABILITY_EX_DESCRIPTION'),
		('ExplorationAgeCivilizations', 'AGE_EXPLORATION',	'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_I', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_I_NAME', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_I_DESCRIPTION'),
		('ExplorationAgeCivilizations', 'AGE_EXPLORATION',	'CIVILIZATION_NYGUITA_ARGENTINA', 'TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_EXPLORATION', 'KIND_TRADITION', 'LOC_TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_EXPLORATION_NAME', 'LOC_TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_EXPLORATION_DESCRIPTION');

INSERT INTO CivilizationItems 
       (CivilizationDomain,       AgeType,       CivilizationType,                 Type,                              Kind,         Name,                                              Description,                                              Icon) 
VALUES ('ModernAgeCivilizations', 'AGE_MODERN',  'CIVILIZATION_NYGUITA_ARGENTINA', 'UNIT_NYGUITA_GAUCHO', 'KIND_UNIT', 'LOC_UNIT_NYGUITA_GAUCHO_NAME', 'LOC_UNIT_NYGUITA_GAUCHO_BASE_DESCRIPTION', 'UNIT_NYGUITA_GAUCHO'),
       ('ModernAgeCivilizations', 'AGE_MODERN',  'CIVILIZATION_NYGUITA_ARGENTINA', 'UNIT_NYGUITA_PORTENO', 'KIND_UNIT', 'LOC_UNIT_NYGUITA_PORTENO_NAME', 'LOC_UNIT_NYGUITA_PORTENO_DESCRIPTION', 'UNIT_NYGUITA_PORTENO'),
       ('ModernAgeCivilizations', 'AGE_MODERN',  'CIVILIZATION_NYGUITA_ARGENTINA', 'QUARTER_NYGUITA_PLAZA_DE_MAYO', 'KIND_QUARTER', 'LOC_QUARTER_NYGUITA_PLAZA_DE_MAYO_NAME', 'LOC_QUARTER_NYGUITA_PLAZA_DE_MAYO_DESCRIPTION', 'QUARTER_NYGUITA_PLAZA_DE_MAYO'),
       ('ModernAgeCivilizations', 'AGE_MODERN',  'CIVILIZATION_NYGUITA_ARGENTINA', 'BUILDING_NYGUITA_BANCO_NACION', 'KIND_BUILDING', 'LOC_BUILDING_NYGUITA_BANCO_NACION_NAME', 'LOC_BUILDING_NYGUITA_BANCO_NACION_DESCRIPTION', 'BUILDING_NYGUITA_BANCO_NACION'),
       ('ModernAgeCivilizations', 'AGE_MODERN',  'CIVILIZATION_NYGUITA_ARGENTINA', 'BUILDING_NYGUITA_SALADERO', 'KIND_BUILDING', 'LOC_BUILDING_NYGUITA_SALADERO_NAME', 'LOC_BUILDING_NYGUITA_SALADERO_DESCRIPTION', 'BUILDING_NYGUITA_SALADERO');
