INSERT INTO LeaderSyncretismUnlocks
        (LeaderType,    UnlockCivilizationType)
VALUES  ('LEADER_PACHACUTI', 'CIVILIZATION_NYGUITA_ARGENTINA'),
        ('LEADER_BOLIVAR', 'CIVILIZATION_NYGUITA_ARGENTINA');

INSERT INTO CivilizationSyncretismUnlocks
        (CivilizationType, UnlockCivilizationType)
VALUES  ('CIVILIZATION_INCA',	'CIVILIZATION_NYGUITA_ARGENTINA'),
		('CIVILIZATION_SPAIN',	'CIVILIZATION_NYGUITA_ARGENTINA');

INSERT INTO CivSelfSyncretismUnlocks
		(CivilizationType,					UnlockType,											Kind,	Age,	ModifierID)
VALUES 	('CIVILIZATION_NYGUITA_ARGENTINA',	'TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_ANTIQUITY',	'KIND_TRADITION',		'AGE_ANTIQUITY',	'MOD_UNLOCK_NYGUITA_ARGENTINA_SYNCRETISM_ANTIQUITY'),
		('CIVILIZATION_NYGUITA_ARGENTINA',	'TRADITION_CULTURE_SLOT',							'KIND_CULTURE_SLOT',	'AGE_ANTIQUITY',	'MOD_SELF_SYNCRETISM_GRANT_TRADITION_SLOT'),
		('CIVILIZATION_NYGUITA_ARGENTINA',	'TRADITION_NYGUITA_ARGENTINA_SYNCRETISM_EXPLORATION',	'KIND_TRADITION',	'AGE_EXPLORATION',	'MOD_UNLOCK_NYGUITA_ARGENTINA_SYNCRETISM_EXPLORATION'),
		('CIVILIZATION_NYGUITA_ARGENTINA',	'TRADITION_CULTURE_SLOT',							'KIND_CULTURE_SLOT',	'AGE_EXPLORATION',	'MOD_SELF_SYNCRETISM_GRANT_TRADITION_SLOT');