INSERT INTO Types 
       (Type,                                       Kind) 
VALUES ('TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT', 'KIND_TRADITION');

INSERT INTO Traditions 
       (TraditionType,                              TraitType,                 AgeType,      Name,                                                Description) 
VALUES ('TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT', 'TRAIT_NYGUITA_ARGENTINA', 'AGE_MODERN', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_NAME', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_DESCRIPTION');


-- MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT
INSERT INTO Types 
       (Type,                                                       Kind) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT_TYPE', 'KIND_MODIFIER'),
       ('ABILITY_NYGUITA_ARGENTINA_CONQUEST_OF_THE_DESERT', 'KIND_ABILITY');

INSERT INTO DynamicModifiers 
       (ModifierType,                                               CollectionType,            EffectType) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT_TYPE', 'COLLECTION_PLAYER_UNITS', 'EFFECT_UNIT_ADJUST_ABILITY');

INSERT INTO Modifiers 
       (ModifierId,                                            ModifierType) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT', 'MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT_TYPE');

INSERT INTO ModifierArguments 
       (ModifierId,                                            Name,          Value) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT', 'AbilityType', 'ABILITY_NYGUITA_ARGENTINA_CONQUEST_OF_THE_DESERT');

INSERT INTO ModifierStrings 
       (ModifierId,                                            Context,       Text) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT', 'Description', 'LOC_MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT_DESCRIPTION');

INSERT INTO TraditionModifiers 
       (ModifierId,                                            TraditionType) 
VALUES ('MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT', 'TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT');

INSERT INTO UnitAbilities
       (UnitAbilityType, Inactive, Description)
VALUES ('ABILITY_NYGUITA_ARGENTINA_CONQUEST_OF_THE_DESERT', 'true', 'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_DESCRIPTION');

INSERT INTO UnitAbilityModifiers
       (UnitAbilityType, ModifierId)
VALUES ('ABILITY_NYGUITA_ARGENTINA_CONQUEST_OF_THE_DESERT', 'INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER');

INSERT INTO Types 
       (Type,                                         Kind) 
VALUES ('INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER_TYPE', 'KIND_MODIFIER');

INSERT INTO DynamicModifiers 
       (ModifierType,                                 CollectionType,           EffectType) 
VALUES ('INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER_TYPE', 'COLLECTION_UNIT_COMBAT', 'EFFECT_ADJUST_UNIT_STRENGTH_MODIFIER');

INSERT INTO Modifiers 
       (ModifierId,                              ModifierType,                                 SubjectRequirementSetId) 
VALUES ('INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER', 'INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER_TYPE', 'REQUIREMENT_OPPONENT_IS_INDEPENDENT');

INSERT INTO ModifierArguments 
       (ModifierId,                              Name,     Value) 
VALUES ('INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER', 'Amount', '5');

INSERT INTO ModifierStrings 
       (ModifierId,                              Context,   Text) 
VALUES ('INDEPENDENT_COMBAT_MINOR_MOD_NYGUITA_CONQUEST_OF_THE_DESERT_ADJUST_UNIT_COMBAT_STRENGTH_MODIFIER', 'Preview', 'LOC_NYGUITA_CONQUEST_OF_THE_DESERT_ABILITY_PREVIEW');
