INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                                                                   Text) 
VALUES ('en_US',  'LOC_MOD_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_COMBAT_DESCRIPTION', '+5 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] against [icon:INDEPENDENT_POWER] [TIP:LOC_PEDIA_CONCEPTS_INDEPENDENT_POWER_TOOLTIP]Independent Powers[/TIP] and [icon:CITYSTATE] City-States.'),
       ('en_US',  'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_NAME', 'Conquest of the Desert'),
       ('en_US',  'LOC_TRADITION_NYGUITA_CONQUEST_OF_THE_DESERT_DESCRIPTION', '+5 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] against [icon:INDEPENDENT_POWER] [TIP:LOC_PEDIA_CONCEPTS_INDEPENDENT_POWER_TOOLTIP]Independent Powers[/TIP] and [icon:CITYSTATE] City-States.'),
       ('en_US',  'LOC_NYGUITA_CONQUEST_OF_THE_DESERT_ABILITY_PREVIEW', 'Against Independent Powers: +5');
