INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                            Text) 
VALUES ('en_US',  'LOC_UNIT_NYGUITA_GAUCHO_NAME', 'Gaucho'),
       ('en_US',  'LOC_PEDIA_PAGE_UNIT_NYGUITA_GAUCHO_CHAPTER_HISTORY_PARA_1', 'Originally an itinerant horseman, hunting wild cattle on the pampas, robbing and smuggling during the 17th century, his image improved due to its patriotism during the Argentine Wars of Independence. A born cavalryman, their jobs were alternating between chasing cattle and fighting during the numerous civil wars and wars of conquest. Their presence on the Argentinian territory decreased after the Great European Migration Wave and the invention of the barbed wire at the end of the 19th century. Since then, it has become a national icon of Argentina in reaction to the rapidly changing way of life brought by the Europeans.'),
       ('en_US',  'LOC_UNIT_NYGUITA_GAUCHO_BASE_DESCRIPTION', 'Argentinian Unique Additional [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Unit[/TIP]. +3 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] when on [TIP:LOC_PEDIA_CONCEPTS_FLAT_TERRAIN_TOOLTIP]Flat Terrain[/TIP]. Doubled when on a farm. Weaker but less expensive to train.'),
       ('en_US',  'LOC_UNIT_NYGUITA_GAUCHO_DESCRIPTION', 'Tier 1 Argentinian Unique Additional [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Unit[/TIP]. +3 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] when on [TIP:LOC_PEDIA_CONCEPTS_FLAT_TERRAIN_TOOLTIP]Flat Terrain[/TIP]. Doubled when on a farm. Weaker but less expensive to train.'),
       ('en_US',  'LOC_UNIT_NYGUITA_GAUCHO_2_DESCRIPTION', 'Tier 2 Argentinian Unique Additional [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Unit[/TIP]. +3 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] when on [TIP:LOC_PEDIA_CONCEPTS_FLAT_TERRAIN_TOOLTIP]Flat Terrain[/TIP]. Doubled when on a farm. Weaker but less expensive to train.'),
       ('en_US',  'LOC_UNIT_NYGUITA_GAUCHO_3_DESCRIPTION', 'Tier 3 Argentinian Unique Additional [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Unit[/TIP]. +3 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] when on [TIP:LOC_PEDIA_CONCEPTS_FLAT_TERRAIN_TOOLTIP]Flat Terrain[/TIP]. Doubled when on a farm. Weaker but less expensive to train.'),
       ('en_US',  'LOC_NYGUITA_GAUCHO_MOD_CS_ON_FLAT_TERRAIN_PREVIEW', '+{1_Value} on flat terrain'),
       ('en_US',  'LOC_NYGUITA_GAUCHO_MOD_CS_ON_FARMS_PREVIEW', '+{1_Value} on farms'),
       ('en_US',  'LOC_ABILITY_NYGUITA_GAUCHO_DESCRIPTION', '+3 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] when on [TIP:LOC_PEDIA_CONCEPTS_FLAT_TERRAIN_TOOLTIP]Flat Terrain[/TIP]. Doubled when on a farm.'),
       ('en_US',  'LOC_ABILITY_NYGUITA_GAUCHO_NAME', 'Boladeros');


