INSERT OR IGNORE INTO LocalizedText 
        (Language,  Tag,                                  Text) 
VALUES  ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE', 'The Purpose of Art'),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_COMPLETION', "With the flourishing culture in our country, many literary groups are created, discussing various matters over a cup of coffee or tea. One striking debate oppose the two biggest groups on the purpose of art. The debate has reached your ears and you can't help yourself thinking over the subject. The purpose of art is..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_NAME', "...to liberate our inner self through aesthetics."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_NAME', "...to communicate and spread our values to shape society."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_NAME', "Let the debate rage on among intellectuals."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_GREATWORK_ARTIFACT_ARGYROSAURUS_NAME', "Argyrosaurus Bones"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE', "The Giants of Patagonia"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_COMPLETION', "While digging in the countryside of our empire, some archeologists seems to have found a skeleton belonging to a very large animal. However, it doesn't seems to match any other animal skeleton that we know of. The large size of the bones makes us believe that the beast would be at least 20 meters in length! Some believe this belong to an ancient species that used to roam the planet before going extinct."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_NAME', "Put it in a museum."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_NAME', "We need to study it more."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE', "Drafting a new constitution"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_COMPLETION', "It seems that our politicians are stuck trying to write a new constitution. Two drafts were already rejected and it seems that the third try will be met with the same fate. The disagreement is between the Unitarianists and the Federalists. The former advocate for a strong central government than can assert its authority on the local provinces while the latter claim that true freedom lies in a federation of provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_NAME', "Support the autonomy of the provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_NAME', "Centralize the power in {1}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_DESCRIPTION', "+1 [icon:YIELD_DIPLOMACY] Influence in every non-Capital [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_DESCRIPTION', "+5 [icon:YIELD_DIPLOMACY] Influence in {2} but -5 [icon:YIELD_HAPPINESS] Happiness in every other [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE', "The Good Doctor in Argentina"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_COMPLETION', "Dr. Rizal stands still in the vastness of the pampas. The Sun of May shines on the arable grasslands where the gauchos keep their cattle. This is a land where everything is yet to be built and conquered."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_NAME', "Ask about the Sun of May."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_NAME', "Learn how they manage the cattle."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_DESCRIPTION', "{1_Reward} on Line Infantry."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_DESCRIPTION', "{1_Reward} in all Settlements."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE', "The Dreadnought Race"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07_COMPLETION', "Our military advisor has warned us about the naval activities of our neighbors. It seems that they have acquired more and more ships to contest our naval dominance. We must quickly react in order quell our minister's concerns."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_NAME', "We must not let them control the sea."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_DESCRIPTION', "Story continues."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_IMPERATIVE', "Build 5 Heavy Naval Units in {1_turn_timer}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_COMPLETION', "The Argentinian navy stands proud and ready to defeat any invasion."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AA_NAME', "Now we need a place to let those ships rest."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AB_NAME', "We have learned a lot about naval construction."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AA_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AB_DESCRIPTION', "{1_Reward} Naval Units."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07B_NAME', "Maybe we can find a diplomatic solution."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08_STORYTITLE', "The Great Migration Wave"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08_COMPLETION', "The story of our riches has reached the faraway lands and now, flocks of migrants are arriving in our ports. The question is now of where they should go as they can't wait eternally in our immigration offices."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08A_NAME', "Let them settle the vast empty lands."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08B_NAME', "Surely our cities already have the infrastructure to receive them."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09_STORYTITLE', "The Conquest of the Desert"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09_COMPLETION', "At the end the battle, a soldier looks around him. A village in flames, natives crying and soaked in blood. This land is no longer theirs and they won't approach our borders anymore. Soon, this land will be flooded with settlers and become beautiful Argentinian land but the pain of the past will never be forgotten."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09A_NAME', "It is time to make peace with them."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09B_NAME', "We must continue until we subdue them all."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09B_DESCRIPTION', "{1_Homeland_Independent} becomes Hostile (removes all progress towards Befriending) and sends a Raid to {2_capital}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10_STORYTITLE', "Yellow faces and Black vomit"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10_COMPLETION', "Three hundred cases of yellow fever were diagnosed in a neighbourhood today. Businesses closed, streets deserted, a shortage of doctors, corpses without assistance, everyone flees if they can... What was supposed to be a carnival day turned out to be a disaster. It seems the disease came from the pollution of the water from our saladeros who threw their debris in the river. While the saladeros promise to do better in the future, we must focus on the current problem: the scrouge of black vomit."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10A_NAME', "We must put them in quarantine."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10B_NAME', "Send them to the hospital!"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11_STORYTITLE', "A curious headdress"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11_COMPLETION', "A new fashion has hit our streets! Rich women have started wearing some sort of giant comb in their hair. These profusely decorated combs, made with tortoiseshell, have become so large that some women have blocked sidewalks because they were too narrow. Despite those impracticalities, they have been sold everywhere under the name of peinetón, especially in the Plaza de Mayo. It seems that no matter you go, peinetónes - and therefore women - have invaded the public space."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11A_NAME', "Bigger is better! I want to see how big they can be."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11B_NAME', "We should put some regulation of their size."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12_STORYTITLE', "The Lame Duck"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12_COMPLETION', "During one of your travels in the countryside, you see a sudden projectile coming your way. After you duck down to avoid it, you examine it and discover that it is a live duck inside a basket! You go to the nearest estância and discover a group of 8 gauchos fighting each other. As knives are getting out, you approach them to try to understand the situation. After ducking and diving for an hour, you understand that they are playing some sort of game where you have to take the basket and try to reach their ranch house. It sounds quite dangerous and some people have already died trampled by the horses. As you see them repairing the basket with cotton duck, you're thinking that you have to do something about it and that you can't just duck out of situation."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12A_NAME', "This game is a dead duck. Ban it."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12B_NAME', "If they get all their ducks in a row, it could be interesting to watch."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13_STORYTITLE', "The Cry of the Land"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13_COMPLETION', "An agrarian rebellion has erupted in one of our towns. The chacareros (immigrant farmers) are asking for better working conditions and better contracts. Until then, they have stopped working the land. Their call have reached the cities and it has become not just a economical problem but also a political one. While the chacareros are just asking for better wages, some more extreme activists on the left side of the political spectrum are asking for a more radical reform of our agricultural policy."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13A_NAME', "Listen to their pleas."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13A_DESCRIPTION', "Settlements gain +2 [icon:YIELD_FOOD] Food but -1 [icon:YIELD_GOLD] Gold for every Rural [icon:YIELD_POPULATION] Population."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13B_NAME', "Wait until the rebellion dies on its own."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13C_NAME', "Actively repress it."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13C_DESCRIPTION', "Three tiles are pillaged in all Towns but 1 Melee Unit in all Towns."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13D_NAME', "The immigrant farmer is also part of the proletariat."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13D_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_CRY_OF_ALCORTA_NAME', "Cry of Alcorta");