INSERT OR IGNORE INTO LocalizedText 
        (Language,  Tag,                                  Text) 
VALUES  ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE', 'The Purpose of Art'),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_COMPLETION', "With the flourishing culture in our country, many literary groups are created, discussing various matters over a cup of coffee or tea. One striking debate oppose the two biggest groups on the purpose of art. The debate has reached your ears and you can't help yourself thinking over the subject. The purpose of art is..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_NAME', "...to liberate our inner self through aesthetics."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_NAME', "...to communicate and spread our values to shape society."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_NAME', "Let the debate rage on among intellectuals."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_GREATWORK_ARTIFACT_ARGYROSAURUS_NAME', "Argyrosaurus Bones"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE', "The Giants of Patagonia"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_COMPLETION', "While digging in the countryside of our empire, some archeologists seems to have found a skeleton belonging to a very large animal. However, it doesn't seems to match any other animal skeleton that we know of. The large size of the bones makes us believe that the beast would be at least 20 meters in length! Some believe this belong to an ancient species that used to roam the planet before going extinct."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_NAME', "Put it in a museum."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_NAME', "We need to study it more."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE', "Drafting a new constitution"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_COMPLETION', "It seems that our politicians are stuck trying to write a new constitution. Two drafts were already rejected and it seems that the third try will be met with the same fate. The disagreement is between the Unitarianists and the Federalists. The former advocate for a strong central government than can assert its authority on the local provinces while the latter claim that true freedom lies in a federation of provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_NAME', "Support the autonomy of the provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_NAME', "Centralize the power in {1}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_DESCRIPTION', "+1 [icon:YIELD_DIPLOMACY] Influence in every non-Capital [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_DESCRIPTION', "+5 [icon:YIELD_DIPLOMACY] Influence in {2} but -5 [icon:YIELD_HAPPINESS] Happiness in every other [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE', "The Good Doctor in Argentina"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_COMPLETION', "Dr. Rizal stands still in the vastness of the pampas. The Sun of May shines on the arable grasslands where the gauchos keep their cattle. This is a land where everything is yet to be built and conquered."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_NAME', "Ask about the Sun of May."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_NAME', "Learn how they manage the cattle."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_DESCRIPTION', "{1_Reward} on Line Infantry."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_DESCRIPTION', "{1_Reward} in all Settlements.");