INSERT OR IGNORE INTO LocalizedText 
        (Language,  Tag,                                  Text) 
VALUES  ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE', 'The Purpose of Art'),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01_COMPLETION', "With the flourishing culture in our country, many literary groups are created, discussing various matters over a cup of coffee or tea. One striking debate oppose the two biggest groups on the purpose of art. The debate has reached your ears and you can't help yourself thinking over the subject. The purpose of art is..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_NAME', "...to liberate our inner self through aesthetics."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_NAME', "...to communicate and spread our values to shape society."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_NAME', "Let the debate rage on among intellectuals."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_01C_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_GREATWORK_ARTIFACT_ARGYROSAURUS_NAME', "Argyrosaurus Bones"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE', "The Giants of Patagonia"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02_COMPLETION', "While digging in the countryside of our empire, some archeologists seems to have found a skeleton belonging to a very large animal. However, it doesn't seems to match any other animal skeleton that we know of. The large size of the bones makes us believe that the beast would be at least 20 meters in length! Some believe this belong to an ancient species that used to roam the planet before going extinct."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_NAME', "Put it in a museum."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_NAME', "We need to study it more."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_02B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE', "Drafting a new constitution"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03_COMPLETION', "It seems that our politicians are stuck trying to write a new constitution. Two drafts were already rejected and it seems that the third try will be met with the same fate. The disagreement is between the Unitarianists and the Federalists. The former advocate for a strong central government than can assert its authority on the local provinces while the latter claim that true freedom lies in a federation of provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_NAME', "Support the autonomy of the provinces."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_NAME', "Centralize the power in {1}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03A_DESCRIPTION', "+1 [icon:YIELD_DIPLOMACY] Influence in every non-Capital [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_03B_DESCRIPTION', "+5 [icon:YIELD_DIPLOMACY] Influence in {2} but -5 [icon:YIELD_HAPPINESS] Happiness in every other [icon:YIELD_CITIES] City."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE', "The Good Doctor in Argentina"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05_COMPLETION', "Dr. Rizal stands still in the vastness of the pampas. The Sun of May shines on the arable grasslands where the gauchos keep their cattle. This is a land where everything is yet to be built and conquered."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_NAME', "Ask about the Sun of May."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_NAME', "Learn how they manage the cattle."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05A_DESCRIPTION', "{1_Reward} on Line Infantry."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_05B_DESCRIPTION', "{1_Reward} in all Settlements."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE', "The Dreadnought Race"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07_COMPLETION', "Our military advisor has warned us about the naval activities of our neighbors. It seems that they have acquired more and more ships to contest our naval dominance. We must quickly react in order quell our minister's concerns."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_NAME', "We must not let them control the sea."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_DESCRIPTION', "Story continues."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_IMPERATIVE', "Build 5 Heavy Naval Units in {1_turn_timer}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_COMPLETION', "The Argentinian navy stands proud and ready to defeat any invasion."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AA_NAME', "Now we need a place to let those ships rest."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AB_NAME', "We have learned a lot about naval construction."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AA_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07AB_DESCRIPTION', "{1_Reward} Naval Units."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07B_NAME', "Maybe we can find a diplomatic solution."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_07B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08_STORYTITLE', "The Great Migration Wave"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08_COMPLETION', "The story of our riches has reached the faraway lands and now, flocks of migrants are arriving in our ports. The question is now of where they should go as they can't wait eternally in our immigration offices."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08A_NAME', "Let them settle the vast empty lands."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08B_NAME', "Surely our cities already have the infrastructure to receive them."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_08B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09_STORYTITLE', "The Conquest of the Desert"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09_COMPLETION', "At the end the battle, a soldier looks around him. A village in flames, natives crying and soaked in blood. This land is no longer theirs and they won't approach our borders anymore. Soon, this land will be flooded with settlers and become beautiful Argentinian land but the pain of the past will never be forgotten."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09A_NAME', "It is time to make peace with them."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09B_NAME', "We must continue until we subdue them all."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_09B_DESCRIPTION', "{1_Homeland_Independent} becomes Hostile (removes all progress towards Befriending) and sends a Raid to {2_capital}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10_STORYTITLE', "Yellow faces and Black vomit"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10_COMPLETION', "Three hundred cases of yellow fever were diagnosed in a neighbourhood today. Businesses closed, streets deserted, a shortage of doctors, corpses without assistance, everyone flees if they can... What was supposed to be a carnival day turned out to be a disaster. It seems the disease came from the pollution of the water from our saladeros who threw their debris in the river. While the saladeros promise to do better in the future, we must focus on the current problem: the scrouge of black vomit."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10A_NAME', "We must put them in quarantine."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10B_NAME', "Send them to the hospital!"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_10B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11_STORYTITLE', "A curious headdress"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11_COMPLETION', "A new fashion has hit our streets! Rich women have started wearing some sort of giant comb in their hair. These profusely decorated combs, made with tortoiseshell, have become so large that some women have blocked sidewalks because they were too narrow. Despite those impracticalities, they have been sold everywhere under the name of peinetón, especially in the Plaza de Mayo. It seems that no matter you go, peinetónes - and therefore women - have invaded the public space."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11A_NAME', "Bigger is better! I want to see how big they can be."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11B_NAME', "We should put some regulation of their size."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_11B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12_STORYTITLE', "The Lame Duck"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12_COMPLETION', "During one of your travels in the countryside, you see a sudden projectile coming your way. After you duck down to avoid it, you examine it and discover that it is a live duck inside a basket! You go to the nearest estância and discover a group of 8 gauchos fighting each other. As knives are getting out, you approach them to try to understand the situation. After ducking and diving for an hour, you understand that they are playing some sort of game where you have to take the basket and try to reach their ranch house. It sounds quite dangerous and some people have already died trampled by the horses. As you see them repairing the basket with cotton duck, you're thinking that you have to do something about it and that you can't just duck out of situation."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12A_NAME', "This game is a dead duck. Ban it."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12B_NAME', "If they get all their ducks in a row, it could be interesting to watch."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_12B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13_STORYTITLE', "The Cry of the Land"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13_COMPLETION', "An agrarian rebellion has erupted in one of our towns. The chacareros (immigrant farmers) are asking for better working conditions and better contracts. Until then, they have stopped working the land. Their call have reached the cities and it has become not just a economical problem but also a political one. While the chacareros are just asking for better wages, some more extreme activists on the left side of the political spectrum are asking for a more radical reform of our agricultural policy."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13A_NAME', "Listen to their pleas."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13A_DESCRIPTION', "Settlements gain +2 [icon:YIELD_FOOD] Food but -1 [icon:YIELD_GOLD] Gold for every Rural [icon:YIELD_POPULATION] Population."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13B_NAME', "Wait until the rebellion dies on its own."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13C_NAME', "Actively repress it."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13C_DESCRIPTION', "Three tiles are pillaged in all Towns but 1 Melee Unit in all Towns."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13D_NAME', "The immigrant farmer is also part of the proletariat."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_13D_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_CRY_OF_ALCORTA_NAME', "Cry of Alcorta"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14_STORYTITLE', "The Oil Battle"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14_COMPLETION', "With the advent of the petrol engine, it seems that we will require more and more oil, both for civilian and military use. As of now, our oil supply is too low to keep up with the demand. In order to continue as a modern nation, we must find a way to get more oil, in the name and for the benefit of national sovereignty." ),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14A_NAME', "We must achieve self-sufficiency no matter what."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14A_DESCRIPTION', "Story continues."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14A_IMPERATIVE', "Have 5 Oil improved."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14A_COMPLETION', "Argentina can now rest as we."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14AA_NAME', "This will save up quite a lot of money."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14AB_NAME', "No more blackout and energy rationing."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14AA_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14AB_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14B_NAME', "There will always be someone willing to trade."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_14B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15_STORYTITLE', "The War of the Triple Alliance"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15_COMPLETION', "As we prepare for war, we has received news about our two allies who will join us in the fight as we unite in a offensive and defensive Alliance. Hearing this has inspired our troops! Nothing will stop us in our way."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15A_NAME', "Victory is upon us!"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15A_DESCRIPTION', "+1 [icon:WAR_SUPPORT] [TIP:LOC_PEDIA_CONCEPTS_WAR_SUPPORT_TOOLTIP]War Support[/TIP] on all [icon:WAR] Wars."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15B_NAME', "It's good to have allies."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_15B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16_STORYTITLE', "The Inca Plan"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16_COMPLETION', "During the drafting of the constitution, it was decided that the Argentinian nation will be a monarchy. But a question was still remaining: Who should be King? While some officers are nominating each others, a surprising proposal was formulated: what about a Sapa Inca? It would gather support from the northern provinces and the indigenous populations as the Incas ruled this land before us. Some folks in {1_Capital} are opposed to this, as they would feel being by some distant king would reduce their own autonomy. They suggest to crown a more European king, in order to get diplomatic relations with the other nations."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16A_NAME', "Ancestors cast the longest shadows."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16B_NAME', "The future only depends on the present."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16C_NAME', "I heard someone in France was interested."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_16C_DESCRIPTION', "{1_Reward} to the French Empire."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17_STORYTITLE', "We Don't Need No Education"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17_COMPLETION', "What should have been the day of going back to school has turned into strikes and protests, as students occupy the faculties' premises, so classes can not be started. Their concerns? A most needed education reform. The education system was mostly provided by the clergy with professors appointed for life by the government. They demand that the State does not interfere anymore in university administration, that curricula must be updated to introduce the most recent scientific discoveries, that tution must be removed to guarantee the right of eduction to every Argentinian citizens and that education programs be free of religious dogmatism. Their uprising has spread to every university in the country and the occupation of faculties won't stop until their demands are met."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17A_NAME', "Grant them autonomy."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17A_DESCRIPTION', "{1_reward}, but {2_reward} on all Science Buildings."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17B_NAME', "Grant free tuition for everybody."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17B_DESCRIPTION', "{1_reward}, but {2_reward} on all Science Buildings."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17C_NAME', "Send in the national army."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_17C_DESCRIPTION', "Free Commander Promotion but {2_reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18_STORYTITLE', "Malón"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18_COMPLETION', "Another raid has happened in our frontiers! Horses were stolen, cattle has been abducted and young women have been captured. The enemy came in a fast surprise attack and targeting our most vulnerable population. By the time reinforcements arrived, they were already gone, leaving us unable to retaliate or pursue them. We must find a solution to this problem."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18A_NAME', "Build some fortifications."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18A_DESCRIPTION', "Three free Defensive Fortifications Purchases."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18B_NAME', "Arm the local population."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_18B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20_STORYTITLE', "The Maté Crisis"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20_COMPLETION', "With the destruction of the temple, the secrets of the domestication of yerba mate are now lost to time. As the drink was made primarily by religious people who knew the best places to grow the plant, the production of maté is at an all time low but consumption of the drink is at a all time high. While originally a drink made by the indigenous Guaraní people, it has since spread to every layer of the Argentine society, especially in mountain shelters where the drink was cheap but homely. Now with the drink more popular than ever, we must find a way to increase our supply of this delicious concoction." ),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20A_NAME', "Increase domestic production by importing migrants."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20B_NAME', "Trade with other nations who produce yerba mate."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20C_NAME', "Maybe we can switch to more civilized drinks like cocoa, coffee or tea."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20C_DESCRIPTION', "Story continues."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20C_IMPERATIVE', "Trade to get Cocoa, Coffee or Tea."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20C_COMPLETION', "As the younger generations now prefer coffee and tea over traditional maté, we have now a surplus of it. But it turns out that some migrants have taken the habit of drinking maté to their homelands, leading us to a lucrative export potential."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20CA_NAME', "A surprise business opportunity but a welcome one."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_20CA_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_GREATWORK_ARTIFACT_DANTE_DEATH_MASK_NAME', "Dante's Death Mask"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21_STORYTITLE', "The House of the Supreme Poet"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21_COMPLETION', "As the Palacio Barolo open its doors, Machiavelli is moved to see such a wonder in honor of one of his hero - Dante Alighieri. Now he wants to add something to make the Palace something worth to il Sommo Poeta."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21A_NAME', "Move his ashes to the Palace."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21B_NAME', "Decorate the walls with scenes of the Divine Comedy."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_21B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22_STORYTITLE', "The Conquest of the Dessert"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22_COMPLETION', "When our politicians were busy drafting the Constitution upper stairs, on the ground floor, a baker was making a delicious confection, made of three puff pastry layers, held together with some dulce de leche and glazed all over. After tasting them, the writers of the constitution took them as a souvenir and spread the alfajor far and beyond in the country. Since then, the confectionery has taken over Argentina, with multiple regional variations and thousands consumed every year. For a while, all those alfajores were hand made but with the advent of mass production, we can make them faster and easier, guaranteeing access for every citizen to this delicious sweet."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22A_NAME', "They're gonna sell like hot cakes."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22B_NAME', "Oh we can't get enough of those."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22C_NAME', "Send weekly deliveries to the military."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_22C_DESCRIPTION', "{1_Reward} on Army Commanders."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23_STORYTITLE', "The Fallout of the Gaucho"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23_COMPLETION', "With the sedentarization and growing urbanization in the empire, the lifestyle of the gaucho is getting less and less popular. While certain appreciate the modernization of the country and the civil stability and social progress that comes with it, many wonder if Argentina doesn't leave some part of itself behind, if Argentina hasn't lost its origin and birthplace in the untamed wilderness."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23A_NAME', "They are now a rastreador. Their knowledge of the land will help us in missing persons cases."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23A_DESCRIPTION', "{1_Reward} and {2_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23B_NAME', "They are now a domador. Their knowledge of husbandry will help us raise the greatest horses and beef."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23B_DESCRIPTION', "+3 [icon:YIELD_PRODUCTION] Production on Pastures."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23C_NAME', "They are now a payador. Their ideology is now a symbol of the Argentinian soul."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_23C_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_NYGUITA_DOMADOR_MODIFIER_TOOLTIP', "Domador"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24_STORYTITLE', "A Mysterious Visitor"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24_COMPLETION', "As you were in your room writing about future plans for the space launch pad, a mysterious stranger suddenly appears out of thin air in your room. He explains that he comes from the future, where a terrible snowstorm has paralyzed the capital. He tells you that this time, the snowstorm was in fact part of an ongoing alien invasion and the snow kills any living being upon touch. He continues with his story of his survival, including escaping as a nuclear bomb is launched towards Argentina. He says that he got his hands on alien technology that enabled him to travel back in time and that's how he suddenly appeared in your room. Upon realizing that he ended up in Argentina again, he flees from your room before you can ask any more question, leaving the place as silent as before he arrived."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24A_NAME', "Write the encounter down."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24A_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24B_NAME', "What a strange hallucination."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24B_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24AA_STORYTITLE', "The aliens are finally here!"),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24AA_COMPLETION', "As the blizzard rages on, you remember the mysterious encounter you had in your room. After publishing the story, the citizens thought it was odd but still was good fiction. As the snowstorm was announced - the first snowstorm in a long time-, a lot of families, maybe unconsciously, stayed more at home and were more prepared, joking how the aliens have finally arrived. After the snow melted, people were shouting joyously how they survived the alien invasion."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24AB_NAME', "Good thing we transcribed that encounter."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24AB_DESCRIPTION', "{1_Reward}."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24BA_STORYTITLE', "On a white and snowy day..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24BA_COMPLETION', "As the blizzard rages on, you remember the mysterious encounter you had in your room. As crowds gather in the streets and parks all over the country to experience snow, many for the first time in their lives, you hear about the frozen lakes in the countryside and children throwing snowballs to reporters trying to do their job. While a few accidents did occur during the night, it seems that joy is the main feeling of your citizens. You can't help but wonder if the snowstorm isn't the sign of more troubling times to come..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24BB_NAME', "Maybe it wasn't an hallucination after all..."),
        ('en_US',   'LOC_EVENT_NYGUITA_ARGENTINA_24BB_DESCRIPTION', "{1_Reward}.");