-- Event 1: A dispute between the Florida and the Boedo group on the purpose of art (Must have researched Tango and Poetry Civic, must have Tea of Coffee and 18 specialists)

INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_01',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_01A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_01B',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_01C',    	    'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_01',  'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_01_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_01_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_01_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_01A', 'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_01A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_01A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_01A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_01B', 'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_01B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_01B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_01B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_01C', 'LOC_EVENT_NYGUITA_ARGENTINA_01_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_01C_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_01C_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_01C_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_01',	'EVENT_NYGUITA_ARGENTINA_01A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_01A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_01A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_01',	'EVENT_NYGUITA_ARGENTINA_01B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_01B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_01B_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_01',	'EVENT_NYGUITA_ARGENTINA_01C',	2,	'LOC_EVENT_NYGUITA_ARGENTINA_01C_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_01C_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A_REWARD',	'EVENT_NYGUITA_ARGENTINA_01A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_01B_REWARD',	'EVENT_NYGUITA_ARGENTINA_01B_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_01C_REWARD',	'EVENT_NYGUITA_ARGENTINA_01C_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A',	'YIELD_CULTURE',	    0),
		('EVENT_NYGUITA_ARGENTINA_01B',	'ATTRIBUTE_CULTURAL',	0),
		('EVENT_NYGUITA_ARGENTINA_01C',	'YIELD_HAPPINESS',		0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A',	'EVENT_NYGUITA_ARGENTINA_01A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_01B',	'EVENT_NYGUITA_ARGENTINA_01B_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_01C',	'EVENT_NYGUITA_ARGENTINA_01C_REWARD',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',		'REQUIREMENTSET_TEST_ALL'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',		'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE_1'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_1'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_3');

INSERT INTO Requirements
		(RequirementId,										RequirementType,									ProgressWeight)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE_1',		'REQUIREMENT_PLAYER_CIVILIZATION_TYPE_MATCHES',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_1',		'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2',		'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_3',		'REQUIREMENT_PLAYER_HAS_X_WORKERS',	1);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE_1',		'CivilizationType',			'CIVILIZATION_NYGUITA_ARGENTINA'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_1',		'GossipTypes',	'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01',	'Hash,ProgressionTreeNodeType,CIVIC_NYGUITA_TANGO_AND_POETRY'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_1',		'Amount',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2',		'GossipTypes',	'GOSSIP_GATHER_RESOURCE01,GOSSIP_GATHER_RESOURCE02'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2',		'GOSSIP_GATHER_RESOURCE01',	'Hash,ResourceType,RESOURCE_TEA'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2',		'GOSSIP_GATHER_RESOURCE02',	'Hash,ResourceType,RESOURCE_COFFEE'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_2',		'Amount',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_01_NARRATIVE_3',		'Amount',	18);

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_01A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_01B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_01B_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_01C_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_01C_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_01B_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_01C_MODIFIER_TYPE',	    'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE'),
		('EVENT_NYGUITA_ARGENTINA_01B_MODIFIER_TYPE',		'COLLECTION_OWNER',		        'EFFECT_PLAYER_ATTRIBUTE'),
		('EVENT_NYGUITA_ARGENTINA_01C_MODIFIER_TYPE',	    'COLLECTION_OWNER',	            'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A_MODIFIER',		'YieldType',	    'YIELD_CULTURE'),
		('EVENT_NYGUITA_ARGENTINA_01A_MODIFIER',		'MultiplierType',	'REWARD_TYPE_MEDIUM_EARLY'),
		('EVENT_NYGUITA_ARGENTINA_01B_MODIFIER',		'AttributeType',	'ATTRIBUTE_CULTURAL'),
		('EVENT_NYGUITA_ARGENTINA_01B_MODIFIER',	    'Amount',		    1),
		('EVENT_NYGUITA_ARGENTINA_01C_MODIFIER',	    'YieldType',		'YIELD_HAPPINESS'),
		('EVENT_NYGUITA_ARGENTINA_01C_MODIFIER',	    'MultiplierType',	'REWARD_TYPE_MEDIUM_EARLY');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_01A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_01B',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_01C',	'REWARD',					'REWARD',							1);

--- Event 2: The discovery of the Argyrosaurus (Have researched Natural History II and must have at least one Archeologist)
INSERT INTO Types
		(Type,								Kind)
VALUES	('GREATWORK_ARTIFACT_ARGYROSAURUS',	'KIND_GREATWORK');

INSERT INTO GreatWorks
		(GreatWorkType,						GreatWorkObjectType,		Name,										Description, 							Generic, 	Image)
VALUES	('GREATWORK_ARTIFACT_ARGYROSAURUS', 'GREATWORKOBJECT_ARTIFACT', 'LOC_GREATWORK_ARTIFACT_ARGYROSAURUS_NAME', 'LOC_GREATWORK_ARTIFACT_DESCRIPTION',	'false',	'fs://game/gw_argyrosaurus_bones.dds');

INSERT INTO GreatWork_YieldChanges
		(GreatWorkType,						YieldType,		YieldChange)
VALUES	('GREATWORK_ARTIFACT_ARGYROSAURUS', 'YIELD_CULTURE', 4);

INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_02',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_02A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_02B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_02',  'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_02_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_02_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_02_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_02A', 'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_02A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_02A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_02A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_02B', 'LOC_EVENT_NYGUITA_ARGENTINA_02_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_02B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_02B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_02B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_02',	'EVENT_NYGUITA_ARGENTINA_02A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_02A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_02A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_02',	'EVENT_NYGUITA_ARGENTINA_02B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_02B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_02B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A_REWARD',	'EVENT_NYGUITA_ARGENTINA_02A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_02B_REWARD',	'EVENT_NYGUITA_ARGENTINA_02B_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A',	'GREATWORK',	    0),
		('EVENT_NYGUITA_ARGENTINA_02B',	'YIELD_SCIENCE',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A',	'EVENT_NYGUITA_ARGENTINA_02A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_02B',	'EVENT_NYGUITA_ARGENTINA_02B_REWARD',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1',		'GossipTypes',	'GOSSIP_TRAIN_UNIT01,GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1',		'GOSSIP_TRAIN_UNIT01',	'Hash,UnitType,UNIT_EXPLORER,Numeric,PlayerCount,1'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02',	'Hash,ProgressionTreeNodeType,NODE_CIVIC_MO_MAIN_NATURAL_HISTORY,Numeric,TreeDepth,2'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_02_NARRATIVE_1',		'Amount',	2);

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_02A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_02B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_02B_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_02B_MODIFIER_TYPE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_GRANT_GREAT_WORK'),
		('EVENT_NYGUITA_ARGENTINA_02B_MODIFIER_TYPE',		'COLLECTION_OWNER',		        'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A_MODIFIER',		'GreatWork',	    'GREATWORK_ARTIFACT_ARGYROSAURUS'),
		('EVENT_NYGUITA_ARGENTINA_02B_MODIFIER',	    'YieldType',		'YIELD_SCIENCE'),
		('EVENT_NYGUITA_ARGENTINA_02B_MODIFIER',	    'MultiplierType',	'REWARD_TYPE_MEDIUM_EARLY');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_02A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_02B',	'REWARD',					'REWARD',							1);

--- Event 3: A new Constitution (Research Congress of Tucuman and Political Theory. Have a least 3 commanders and 5 cities.)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_03',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_03A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_03B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_03',  'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_03_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_03_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_03_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_03A', 'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_03A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_03A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_03A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_03B', 'LOC_EVENT_NYGUITA_ARGENTINA_03_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_03B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_03B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_03B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_03',	'EVENT_NYGUITA_ARGENTINA_03A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_03A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_03A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_03',	'EVENT_NYGUITA_ARGENTINA_03B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_03B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_03B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A_REWARD',	'EVENT_NYGUITA_ARGENTINA_03A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_03B_REWARD',	'EVENT_NYGUITA_ARGENTINA_03B_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_03B_REWARD2',	'EVENT_NYGUITA_ARGENTINA_03B_MODIFIER2');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A',	'YIELD_DIPLOMACY',	    0),
		('EVENT_NYGUITA_ARGENTINA_03B',	'YIELD_DIPLOMACY',	0),
		('EVENT_NYGUITA_ARGENTINA_03B',	'YIELD_HAPPINESS',	1);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A',	'EVENT_NYGUITA_ARGENTINA_03A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_03B',	'EVENT_NYGUITA_ARGENTINA_03B_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_03B',	'EVENT_NYGUITA_ARGENTINA_03B_REWARD2',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_3'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',		'REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',		'REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_2');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight,	inverse)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2',	'REQUIREMENT_PLAYER_HAS_X_SETTLEMENTS',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_3',	'REQUIREMENT_PLAYER_HAS_COMMANDERS_WITH_X_LEVELS',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_1',	'REQUIREMENT_CITY_IS_CITY',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_2',	'REQUIREMENT_CITY_HAS_BUILDING',	1,	1);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1',		'GossipTypes',	'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01,GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01',	'Hash,ProgressionTreeNodeType,CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02',	'Hash,ProgressionTreeNodeType,NODE_CIVIC_MO_MAIN_POLITICAL_THEORY'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_1',		'Amount',	2),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2',		'OnlyCities',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2',		'CountPerConqueredSettlement',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2',		'CountPerOwnSettlement',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_2',		'RequiredCount',	5),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_3',		'CommanderCount',	3),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03_NARRATIVE_3',		'LevelCount',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_2',		'BuildingType',	'BUILDING_PALACE');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_TYPE',			'REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',						1),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER2',			'EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE2',			'REQSET_EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE2',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A_MODIFIER_TYPE',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_YIELD'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_CONSTRUCTIBLE_YIELD'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER_TYPE2',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_YIELD');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',		'YieldType',		'YIELD_DIPLOMACY'),
		('EVENT_NYGUITA_ARGENTINA_03A_MODIFIER',		'Amount',	1),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER',	    'YieldType',		'YIELD_DIPLOMACY'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER',	    'Amount',	5),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER',	    'ConstructibleType',	'BUILDING_PALACE'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER2',		'YieldType',		'YIELD_HAPPINESS'),
		('EVENT_NYGUITA_ARGENTINA_03B_MODIFIER2',		'Amount',	-5);

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_03A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_03B',	'OPTION',					'CAPITAL',							1),
        ('EVENT_NYGUITA_ARGENTINA_03B',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_03B',	'REWARD',					'CAPITAL',							2);

--- Event 4: Britain settles too close to us (Falklands) TODO
--- Event 5: The Good Doctor in Argentina

INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_05',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_05A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_05B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_05',  'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_05_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_05_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_05_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'UNLOCKED',    '3DPANEL', null,  'REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_05A', 'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_05A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_05A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_05A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_05B', 'LOC_EVENT_NYGUITA_ARGENTINA_05_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_05B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_05B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_05B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('291D',						'EVENT_NYGUITA_ARGENTINA_05',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_05_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_05_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_05',	'EVENT_NYGUITA_ARGENTINA_05A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_05A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_05A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_05',	'EVENT_NYGUITA_ARGENTINA_05B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_05B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_05B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A_REWARD',	'EVENT_NYGUITA_ARGENTINA_05A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_05B_REWARD',	'EVENT_NYGUITA_ARGENTINA_05B_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A',	'CUSTOM',	    0),
		('EVENT_NYGUITA_ARGENTINA_05B',	'YIELD_FOOD',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A',	'EVENT_NYGUITA_ARGENTINA_05A_REWARD',	'START'),
		('EVENT_NYGUITA_ARGENTINA_05B',	'EVENT_NYGUITA_ARGENTINA_05B_REWARD',	'START');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE',		'REQ_STORY_LEADER_JOSE_RIZAL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER',		'REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_1');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_1',	'REQUIREMENT_UNIT_TYPE_MATCHES',	1);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE_1',		'GossipTypes',	'GOSSIP_TRADE_ROUTE_STARTED01'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE_1',		'GOSSIP_TRADE_ROUTE_STARTED01',	'Hash,OtherPlayer,Other,Hash,Civilization,CIVILIZATION_NYGUITA_ARGENTINA'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_05_NARRATIVE_1',		'Amount',	1),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_1',		'UnitType',	'UNIT_LINE_INFANTRY');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_TYPE',			'REQSET_EVENT_NYGUITA_ARGENTINA_05A_MODIFIER',																1),
		('EVENT_NYGUITA_ARGENTINA_05B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_05B_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_05B_MODIFIER_TYPE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A_MODIFIER_TYPE',		'COLLECTION_PLAYER_UNITS',		'EFFECT_UNIT_ADJUST_ABILITY'),
		('EVENT_NYGUITA_ARGENTINA_05B_MODIFIER_TYPE',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_YIELD');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A_MODIFIER',		'AbilityType',	    'ABILITY_NARRATIVE_AGGRESSION'),
		('EVENT_NYGUITA_ARGENTINA_05B_MODIFIER',	    'YieldType',		'YIELD_FOOD'),
		('EVENT_NYGUITA_ARGENTINA_05B_MODIFIER',	    'Amount',	3);

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_05A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_05B',	'REWARD',					'REWARD',							1);

--- Event 6: The Crossing of the Andes (Defeating a unit next to a mountain) TODO
--- Event 7: The South American Dreadnought race (Research Militarism and have at least one naval unit, Quest to build 5 heavy ships, reward between +25% production towards naval units or +25% production towards ports)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_07',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_07A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_07AA',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_07AB',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_07B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId, Timeout, ShowProgress)
VALUES  ('EVENT_NYGUITA_ARGENTINA_07',  'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_07_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_07_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_07_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE', null, 0),
        ('EVENT_NYGUITA_ARGENTINA_07A', 'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_07A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_07A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_07A_COMPLETION',   'LOC_EVENT_NYGUITA_ARGENTINA_07A_IMPERATIVE',   'AGE_MODERN',   1,  0,  'LINKED',       'STANDARD', null, 'REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE', 15, 1),
        ('EVENT_NYGUITA_ARGENTINA_07AA', 'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_07AA_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_07AA_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_07AA_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null, 'Met', null, 0),
        ('EVENT_NYGUITA_ARGENTINA_07AB', 'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_07AB_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_07AB_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_07AB_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null, 'Met', null, 0),
        ('EVENT_NYGUITA_ARGENTINA_07B', 'LOC_EVENT_NYGUITA_ARGENTINA_07_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_07B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_07B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_07B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null, 'Met', null, 0);

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_07',	'EVENT_NYGUITA_ARGENTINA_07A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_07A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_07A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_07',	'EVENT_NYGUITA_ARGENTINA_07B',	1,  'LOC_EVENT_NYGUITA_ARGENTINA_07B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_07B_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_07A',	'EVENT_NYGUITA_ARGENTINA_07AA',	0,	'LOC_EVENT_NYGUITA_ARGENTINA_07AA_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_07AA_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_07A',	'EVENT_NYGUITA_ARGENTINA_07AB',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_07AB_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_07AB_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA_REWARD',	'EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_07AB_REWARD',	'EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_07B_REWARD',	'EVENT_NYGUITA_ARGENTINA_07B_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_07A',	'CUSTOM',	    0),
		('EVENT_NYGUITA_ARGENTINA_07A',	'QUEST',	    0),
		('EVENT_NYGUITA_ARGENTINA_07B',	'YIELD_DIPLOMACY',	    0),
		('EVENT_NYGUITA_ARGENTINA_07AB',	'YIELD_PRODUCTION',	0),
		('EVENT_NYGUITA_ARGENTINA_07AB',	'UNIT_DREADNOUGHT',	0),
		('EVENT_NYGUITA_ARGENTINA_07AA',	'YIELD_PRODUCTION',	0),
		('EVENT_NYGUITA_ARGENTINA_07AA',	'BUILDING_PORT',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA',	'EVENT_NYGUITA_ARGENTINA_07AA_REWARD',	'START'),
		('EVENT_NYGUITA_ARGENTINA_07AB',	'EVENT_NYGUITA_ARGENTINA_07AB_REWARD',	'START'),
		('EVENT_NYGUITA_ARGENTINA_07B',		'EVENT_NYGUITA_ARGENTINA_07B_REWARD',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE',	'REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1),
		('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1',		'GossipTypes',	'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01,GOSSIP_TRAIN_UNIT02'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01',	'Hash,ProgressionTreeNodeType,NODE_CIVIC_MO_MAIN_MILITARISM'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1',		'GOSSIP_TRAIN_UNIT02',	'Hash,DomainType,DOMAIN_SEA'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07_NARRATIVE_1',		'Amount',	2),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1',		'GossipTypes',	'GOSSIP_TRAIN_UNIT01'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1',		'GOSSIP_TRAIN_UNIT01',	'Hash,DomainType,DOMAIN_SEA,Hash,RangedUnit,True'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1',		'AfterInit','1'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_07A_NARRATIVE_1',		'DuplicateCount','5');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_07B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_07B_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_07B_MODIFIER_TYPE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER_TYPE',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_CONSTRUCTIBLE_PRODUCTION'),
		('EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER_TYPE',		'COLLECTION_PLAYER_CITIES',		'EFFECT_CITY_ADJUST_UNIT_PRODUCTION'),
		('EVENT_NYGUITA_ARGENTINA_07B_MODIFIER_TYPE',		'COLLECTION_OWNER',		        'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER',		'Percent',	    25),
		('EVENT_NYGUITA_ARGENTINA_07AA_MODIFIER',		'ConstructibleType',	    'BUILDING_PORT'),
		('EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER',	    'Percent',		25),
		('EVENT_NYGUITA_ARGENTINA_07AB_MODIFIER',	    'Domain',	'DOMAIN_SEA'),
		('EVENT_NYGUITA_ARGENTINA_07B_MODIFIER',	    'YieldType',		'YIELD_DIPLOMACY'),
		('EVENT_NYGUITA_ARGENTINA_07B_MODIFIER',	    'MultiplierType',	'REWARD_TYPE_MEDIUM_EARLY');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_07AA',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_07AB',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_07A',		'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_07A',		'IMPERATIVE',				'TURN_TIMER',						1),
        ('EVENT_NYGUITA_ARGENTINA_07B',		'REWARD',					'REWARD',							1);

--- Event 8: European Migration Wave (Congress of Tucuman II, Steam machine, have at least 2 ports and Living Standards policy card)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_08',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_08A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_08B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_08',  'LOC_EVENT_NYGUITA_ARGENTINA_08_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_08_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_08_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_08_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_08A', 'LOC_EVENT_NYGUITA_ARGENTINA_08_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_08A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_08A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_08A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_08B', 'LOC_EVENT_NYGUITA_ARGENTINA_08_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_08B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_08B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_08B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_08',	'EVENT_NYGUITA_ARGENTINA_08A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_08A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_08A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_08',	'EVENT_NYGUITA_ARGENTINA_08B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_08B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_08B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A_REWARD',	'EVENT_NYGUITA_ARGENTINA_08A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_08B_REWARD',	'EVENT_NYGUITA_ARGENTINA_08B_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A',	'CUSTOM',	0),
		('EVENT_NYGUITA_ARGENTINA_08B',	'CUSTOM',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A',	'EVENT_NYGUITA_ARGENTINA_08A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_08B',	'EVENT_NYGUITA_ARGENTINA_08B_REWARD',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_2');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight,	inverse)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',	'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_2',	'REQUIREMENT_PLAYER_HAS_ACTIVE_TRADITION',	1,	0);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',		'GossipTypes',	'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01,GOSSIP_CONSTRUCT_BUILDING02,GOSSIP_COMPLETED_PROGRESSION_TREE_NODE03'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01',	'Hash,ProgressionTreeNodeType,CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN,Numeric,TreeDepth,2'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',		'GOSSIP_CONSTRUCT_BUILDING02',	'Hash,ConstructibleType,BUILDING_PORT,Numeric,PlayerCount,2'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE03',	'Hash,ProgressionTreeNodeType,NODE_TECH_MO_STEAM_ENGINE'),
        ('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_1',		'Amount',	3),
		('REQSET_EVENT_NYGUITA_ARGENTINA_08_NARRATIVE_2',		'TraditionType',	'TRADITION_LIVING_STANDARDS');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_08A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_08B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_08B_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_08B_MODIFIER_TYPE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A_MODIFIER_TYPE',		'COLLECTION_PLAYER_CAPITAL_CITY',		'EFFECT_CITY_GRANT_UNIT'),
		('EVENT_NYGUITA_ARGENTINA_08B_MODIFIER_TYPE',		'COLLECTION_PLAYER_CAPITAL_CITY',		'EFFECT_CITY_GRANT_UNIT');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A_MODIFIER',		'UnitType',		'UNIT_NYGUITA_PORTENO'),
		('EVENT_NYGUITA_ARGENTINA_08A_MODIFIER',		'Amount',	1),
		('EVENT_NYGUITA_ARGENTINA_08B_MODIFIER',	    'UnitType',		'UNIT_MIGRANT'),
		('EVENT_NYGUITA_ARGENTINA_08B_MODIFIER',	    'Amount',	3);

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_08A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_08B',	'REWARD',					'REWARD',							1);

--- Event 9: The Conquest of the Desert (Disperse an IP)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_09',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_09A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_09B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_09',  'LOC_EVENT_NYGUITA_ARGENTINA_09_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_09_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_09_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_09_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_09A', 'LOC_EVENT_NYGUITA_ARGENTINA_09_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_09A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_09A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_09A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_09B', 'LOC_EVENT_NYGUITA_ARGENTINA_09_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_09B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_09B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_09B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_09',	'EVENT_NYGUITA_ARGENTINA_09A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_09A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_09A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_09',	'EVENT_NYGUITA_ARGENTINA_09B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_09B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_09B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A_REWARD',	'EVENT_NYGUITA_ARGENTINA_09A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_09B_REWARD',	'EVENT_NYGUITA_ARGENTINA_09B_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_09B_REWARD2',	'EVENT_NYGUITA_ARGENTINA_09B_MODIFIER2');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A',	'YIELD_DIPLOMACY',	0),
		('EVENT_NYGUITA_ARGENTINA_09B',	'CUSTOM',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A',	'EVENT_NYGUITA_ARGENTINA_09A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_09B',	'EVENT_NYGUITA_ARGENTINA_09B_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_09B',	'EVENT_NYGUITA_ARGENTINA_09B_REWARD2',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_2');

INSERT INTO Requirements
		(RequirementId,										RequirementType,								ProgressWeight,	inverse)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_1',	'REQUIREMENT_PLAYER_DIPLOMACY_INDEPENDENT_UPDATE_TYPE_MATCHES',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_2',	'REQUIREMENT_PLAYER_HAS_ACTIVE_TRADITION',	1,	0);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_1',		'DiplomacyIndependentUpdateType',	'DIPLOMACY_INDEPENDENT_DISPERSED'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_09_NARRATIVE_2',		'TraditionType',	'TRADITION_LIVING_STANDARDS');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_09A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER2',			'EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE2',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE2',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE',		'COLLECTION_HOMELANDS_INDEPENDENT_NEAREST_STORY',		'EFFECT_CHANGE_INDEPENDENT_AT_LOCATION_INVESTMENT'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER_TYPE2',		'COLLECTION_HOMELANDS_INDEPENDENT_NEAREST_STORY',		'EFFECT_PLAYER_FORCE_MILITARY_OPERATION');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A_MODIFIER',		'YieldType',		'YIELD_DIPLOMACY'),
		('EVENT_NYGUITA_ARGENTINA_09A_MODIFIER',		'MultiplierType',	'REWARD_TYPE_MEDIUM_EARLY'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER',	    'Set',		'TRUE'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER',	    'Amount',	0),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER',	    'Reveal',	'TRUE'),
		('EVENT_NYGUITA_ARGENTINA_09B_MODIFIER2',	    'OperationName',	'INDEPENDENT RAID');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_09A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_09B',	'REWARD',					'HOMELAND_INDEPENDENT',				1),
        ('EVENT_NYGUITA_ARGENTINA_09B',	'REWARD',					'CAPITAL',							2);

--- Event 10: Yellow Fever Epidemic (Building a Saladero next to a river)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_10',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_10A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_10B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_10',  'LOC_EVENT_NYGUITA_ARGENTINA_10_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_10_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_10_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_10_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_10A', 'LOC_EVENT_NYGUITA_ARGENTINA_10_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_10A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_10A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_10A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_10B', 'LOC_EVENT_NYGUITA_ARGENTINA_10_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_10B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_10B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_10B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED_REQUISITE',       'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE', 'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_10',	'EVENT_NYGUITA_ARGENTINA_10A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_10A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_10A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_10',	'EVENT_NYGUITA_ARGENTINA_10B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_10B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_10B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A_REWARD',	'EVENT_NYGUITA_ARGENTINA_10A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_10B_REWARD',	'EVENT_NYGUITA_ARGENTINA_10B_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_10B_REWARD2',	'EVENT_NYGUITA_ARGENTINA_10B_MODIFIER2');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A',	'YIELD_FOOD',	1),
		('EVENT_NYGUITA_ARGENTINA_10B',	'YIELD_HAPPINESS',	0),
		('EVENT_NYGUITA_ARGENTINA_10B',	'YIELD_FOOD',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A',	'EVENT_NYGUITA_ARGENTINA_10A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_10B',	'EVENT_NYGUITA_ARGENTINA_10B_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_10B',	'EVENT_NYGUITA_ARGENTINA_10B_REWARD2',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_2'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE',		'SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE_1');

INSERT INTO Requirements
		(RequirementId,											RequirementType,								ProgressWeight,	inverse)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',		'REQUIREMENT_COLLECTION_ANY_MET',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_2',		'REQUIREMENT_PLAYER_IS_IN_GOLDEN_AGE',	1,	0),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',	'REQUIREMENT_BUILDING_IS_ADJACENT_TO_X',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE_1',		'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS',	1,	0);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',		'CollectionType',	'COLLECTION_PLAYER_CITIES'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',		'RequirementSetId',	'SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',		'BuildingType',	'BUILDING_NYGUITA_SALADERO'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_10_NARRATIVE_1',		'AdjacentTerrainTypes',	'TERRAIN_NAVIGABLE_RIVER'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE_1',		'BuildingType',	'BUILDING_HOSPITAL'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_10B_NARRATIVE_1',		'Amount',	'1');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_10A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER2',			'EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE2',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE2',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_MODIFY_PLAYER_YIELD_FOR_X_TURNS'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER_TYPE2',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER',		'YieldType',		'YIELD_FOOD'),
		('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER',		'ReductionPercent',	'50'),
		('EVENT_NYGUITA_ARGENTINA_10A_MODIFIER',		'Turns',	'3'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER',	    'YieldType',		'YIELD_HAPPINESS'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER',	    'MultiplierType',	'REWARD_TYPE_MINOR_EARLY'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER2',	    'YieldType',	'YIELD_FOOD'),
		('EVENT_NYGUITA_ARGENTINA_10B_MODIFIER2',	    'MultiplierType',	'REWARD_TYPE_MINOR_EARLY');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_10A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_10B',	'REWARD',					'REWARD',							1);

--- Event 11: Peinetón (Research Capitalism and Nationalism, have Turtle and a Plaza de Mayo)
INSERT INTO Types
		(Type,                          Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_11',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_11A',    		'KIND_NARRATIVE_STORY'),
        ('EVENT_NYGUITA_ARGENTINA_11B',    		'KIND_NARRATIVE_STORY');

INSERT INTO NarrativeStories
        (NarrativeStoryType,            StoryTitle,                                     Name,                                   Description,                                    Completion,                                     Imperative, Age,       IsQuest,  Hidden, Activation, UIActivation,   ActivationRequirementSetId,            RequirementSetId)
VALUES  ('EVENT_NYGUITA_ARGENTINA_11',  'LOC_EVENT_NYGUITA_ARGENTINA_11_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_11_NAME',  'LOC_EVENT_NYGUITA_ARGENTINA_11_DESCRIPTION',   'LOC_EVENT_NYGUITA_ARGENTINA_11_COMPLETION',    null,   'AGE_MODERN',   0,  0,  'REQUISITE',    'STANDARD', 'REQSET_EVENT_NYGUITA_ARGENTINA_01_REQUISITE',  'REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE'),
        ('EVENT_NYGUITA_ARGENTINA_11A', 'LOC_EVENT_NYGUITA_ARGENTINA_11_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_11A_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_11A_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_11A_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null,                                           'Met'),
        ('EVENT_NYGUITA_ARGENTINA_11B', 'LOC_EVENT_NYGUITA_ARGENTINA_11_STORYTITLE',    'LOC_EVENT_NYGUITA_ARGENTINA_11B_NAME', 'LOC_EVENT_NYGUITA_ARGENTINA_11B_DESCRIPTION',  'LOC_EVENT_NYGUITA_ARGENTINA_11B_COMPLETION',   null,   'AGE_MODERN',   0,  1,  'LINKED',       'STANDARD', null, 											'Met');

INSERT INTO NarrativeStory_Links
		(FromNarrativeStoryType,		ToNarrativeStoryType,		Priority,	Name,									Description,									Imperative)
VALUES	('EVENT_NYGUITA_ARGENTINA_11',	'EVENT_NYGUITA_ARGENTINA_11A',	0,  'LOC_EVENT_NYGUITA_ARGENTINA_11A_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_11A_DESCRIPTION',		null),
		('EVENT_NYGUITA_ARGENTINA_11',	'EVENT_NYGUITA_ARGENTINA_11B',	1,	'LOC_EVENT_NYGUITA_ARGENTINA_11B_NAME',	'LOC_EVENT_NYGUITA_ARGENTINA_11B_DESCRIPTION',		null);

INSERT INTO NarrativeRewards
		(NarrativeRewardType,				ModifierID)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A_REWARD',	'EVENT_NYGUITA_ARGENTINA_11A_MODIFIER'),
        ('EVENT_NYGUITA_ARGENTINA_11B_REWARD',	'EVENT_NYGUITA_ARGENTINA_11B_MODIFIER');

INSERT INTO NarrativeRewardIcons
		(NarrativeStoryType,			RewardIconType,			Negative)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A',	'YIELD_GOLD',	0),
		('EVENT_NYGUITA_ARGENTINA_11B',	'YIELD_HAPPINESS',	0);

INSERT INTO NarrativeStory_Rewards
		(NarrativeStoryType,			NarrativeRewardType,				Activation)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A',	'EVENT_NYGUITA_ARGENTINA_11A_REWARD',	'COMPLETE'),
		('EVENT_NYGUITA_ARGENTINA_11B',	'EVENT_NYGUITA_ARGENTINA_11B_REWARD',	'COMPLETE');

INSERT INTO RequirementSets
		(RequirementSetId,									RequirementSetType)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE',     'REQUIREMENTSET_TEST_ALL'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE',     'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,									RequirementId)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE',		'REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE',		'SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1');

INSERT INTO Requirements
		(RequirementId,											RequirementType,								ProgressWeight,	inverse)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1',		'REQUIREMENT_COLLECTION_ANY_MET',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2',		'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1,	0),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_GOSSIPS',	1,	0),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1',	'REQUIREMENT_CITY_HAS_UNIQUE_QUARTER',	1,	0);

INSERT INTO RequirementArguments
		(RequirementId,										Name,						Value)
VALUES	('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1',		'CollectionType',	'COLLECTION_PLAYER_CITIES'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1',		'RequirementSetId',	'SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE'),
		('SUBREQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_1',	'UniqueQuarterType',	'QUARTER_NYGUITA_PLAZA_DE_MAYO'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2',		'GossipTypes',	'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01,GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02,'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE01',	'Hash,ProgressionTreeNodeType,NODE_CIVIC_MO_MAIN_CAPITALISM'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2',		'GOSSIP_COMPLETED_PROGRESSION_TREE_NODE02',	'Hash,ProgressionTreeNodeType,NODE_CIVIC_MO_MAIN_NATIONALISM'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_2',		'Amount',	'2'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'GossipTypes',	'GOSSIP_GATHER_RESOURCE01,GOSSIP_GATHER_RESOURCE02,GOSSIP_GATHER_RESOURCE03'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'GOSSIP_GATHER_RESOURCE01',	'Hash,ResourceType,RESOURCE_PEARLS'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'GOSSIP_GATHER_RESOURCE02',	'Hash,ResourceType,RESOURCE_IVORY'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'GOSSIP_GATHER_RESOURCE03',	'Hash,ResourceType,RESOURCE_COWRIE'),
		('REQSET_EVENT_NYGUITA_ARGENTINA_11_NARRATIVE_3',		'Amount',	'2');

INSERT INTO Modifiers
		(ModifierId,									ModifierType,										SubjectRequirementSetId,											Permanent)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_11A_MODIFIER_TYPE',			null,																1),
		('EVENT_NYGUITA_ARGENTINA_11B_MODIFIER',			'EVENT_NYGUITA_ARGENTINA_11B_MODIFIER_TYPE',			null,																1);

INSERT INTO Types
		(Type,												Kind)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A_MODIFIER_TYPE',		'KIND_MODIFIER'),
		('EVENT_NYGUITA_ARGENTINA_11B_MODIFIER_TYPE',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
		(ModifierType,										CollectionType,					EffectType)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE'),
		('EVENT_NYGUITA_ARGENTINA_11B_MODIFIER_TYPE',		'COLLECTION_OWNER',				'EFFECT_PLAYER_GRANT_YIELD_NARRATIVE');

INSERT INTO ModifierArguments
		(ModifierId,									Name,				Value)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A_MODIFIER',	    'YieldType',		'YIELD_GOLD'),
		('EVENT_NYGUITA_ARGENTINA_11A_MODIFIER',	    'MultiplierType',			'REWARD_TYPE_MEDIUM_LATE'),
		('EVENT_NYGUITA_ARGENTINA_11B_MODIFIER',	    'YieldType',		'YIELD_HAPPINESS'),
		('EVENT_NYGUITA_ARGENTINA_11B_MODIFIER',	    'MultiplierType',			'REWARD_TYPE_MEDIUM_LATE');

INSERT INTO NarrativeStory_TextReplacements
		(NarrativeStoryType,			NarrativeStoryTextType,		NarrativeTextReplacementType,		Priority)
VALUES	('EVENT_NYGUITA_ARGENTINA_11A',	'REWARD',					'REWARD',							1),
        ('EVENT_NYGUITA_ARGENTINA_11B',	'REWARD',					'REWARD',							1);

--- Event 12: The rise of polo/pato (Have 4 Horses)
--- Event 13: Cry of Alcorta (Unhappy settlement with 10 rural tiles)
--- Event 14: The Oil Battle (Research Combustion, have less than 3 Oil)
--- Event 15: War of the Triple Alliance (Being in a war with two allies) (choice between War support and influence)
--- Event 16: The Inca plan (Was Inca, research Congress of Tucuman, is Bureaucratic Monarchy)
--- Event 17: Argentine university reform of 1918 (Must have 3 Schoolhouses)
--- Event 18: Malón (IP pillaging a tile)
--- Event 19: Tierra del Fuego gold rush (Settlement in Tundra with access to gold)
--- Event 20: Maté (Have 3 Teas, 3 Coffees and 3 Gauchos)
--- Event 21: Building the Palacio Barolo as Machiavelli
--- Event 22: The Conquest of Dessert (Alfajor, mass production, have 5 sugar)
--- Event 23: The Fallout of the Gaucho (Must have Civilization and Barbarism II, Urbanization, now the gaucho is a rastreador (+happiness) or domador (bonus on pastures) vs a symbol of the Argentinian soul (+culture, must have researched tango & poetry))
