INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                                                                               Text) 
VALUES ('en_US',  'LOC_TREE_NYGUITA_ARGENTINA_NAME', 'Argentinian Civics'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_NAME', 'Congress of Tucumán'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_NAME', 'Civilization and Barbarism'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_NAME', 'Tango and Poetry'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_QUOTE', 'The soldiers of our land know no luxury, but glory.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_AUTHOR', 'José de San Martín'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_QUOTE', 'One does not renounce such an immense future, such a lofty mission, because of an accumulation of contradictions and difficulties. Difficulties are overcome: contradictions are overcome by contradicting them.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_AUTHOR', 'Domingo Faustino Sarmiento'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_QUOTE', 'A writer — and, I believe, generally all persons — must think that whatever happens to him or her is a resource. All things have been given to us for a purpose, and an artist must feel this more intensely.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_AUTHOR', 'Jorge Luis Borges');

INSERT INTO LocalizedText
        (Tag, Language, Text)
VALUES  ('LOC_MOD_NYGUITA_GREAT_EUROPEAN_MIGRATION_WAVE_DESCRIPTION',	'en_US', '+15% Growth in all settlements.'),
        ('LOC_MOD_NYGUITA_VASTNESS_OF_THE_PAMPAS_DESCRIPTION', 		'en_US', '+1 [icon:SETTLEMENT_LIMIT] Settlement limit.'),
        ('LOC_MOD_NYGUITA_LIGA_DE_GOBERNADORES_DESCRIPTION',		'en_US', '+5 [icon:YIELD_GOLD] Gold per Tradition slotted.'),
        ('LOC_MOD_NYGUITA_PATRIA_GRANDE_DESCRIPTION',			'en_US','+1 [icon:SETTLEMENT_LIMIT] Settlement limit.'),
  	('LOC_MOD_NYGUITA_FLORIDA_AND_BOEDO_DESCRIPTION',		'en_US','+5 [icon:YIELD_CULTURE] Culture per non-Tradition slotted.'),
  	('LOC_MOD_NYGUITA_GIANTS_OF_PATAGONIA_DESCRIPTION',		'en_US','+30% [icon:YIELD_PRODUCTION] Production towards Archeologists. +3 [icon:YIELD_SCIENCE] Science on [icon:GREATWORK] Artifacts.');

INSERT OR IGNORE INTO LocalizedText 
       	(Language, Tag,                                       Text) 
VALUES 	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_CHAPTER_HISTORY_PARA_1',  'The Congress of Tucuman was the representative assembly, initially meeting in San Miguel de Tucumán, that declared the independence of the United Provinces of South America on July 9, 1816, from the Spanish Empire. Delegate deputies, each representing 15,000 inhabitants, were sent from all the provinces to the sessions that started on March 24, 1816. After the declaration of independence, subsequent discussions centred on the form of government that the young state should have and were the Congress and the executive power should reside. The Congress was dissolved in 1820 after the Federal League Provinces of Santa Fe and Entre Ríos defeated a diminished Directorship army at the Battle of Cepeda.'),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_CHAPTER_HISTORY_PARA_1',  "Facundo: Civilization and Barbarism is a book written in 1845 by Domingo Faustino Sarmiento, a writer and journalist who would become the second President of the Argentine Republic between 1868 and 1874. It defines the conditions the development of the region, as well as money, power and culture. The dichotomy between civilization and barbarism is the book's central idea; Facundo Quiroga is portrayed as wild, untamed, and standing opposed to true progress through his rejection of European cultural ideals. The conflict between civilization and barbarism mirrors Latin America's difficulties in the post-Independence era."),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_TANGO_AND_POETRY_CHAPTER_HISTORY_PARA_1',  "Argentina has a detailed literary history, as well as one of the region's most active publishing industries. Argentine writers have figured prominently in Latin American literature, since becoming a fully united entity in the 1850s, with a strong constitution and a defined nation-building plan. The struggle between the Federalists and the Unitarians, set the tone for Argentine literature of the time. With the many waves of immigrations, multiple influences rose up. After adopting French romanticism as a model with the Literatura Gauchesca, it was followed by the modernist and vanguardism movement with figures like Ricardo Güiraldes, Roberto Arlt and Victoria Ocampo."),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_TANGO_AND_POETRY_CHAPTER_HISTORY_PARA_2',  "But those immigration waves also brought social tensions and conflicts. Under the Argentine government's efforts to Europeanize and modernize the country, those who did not fit the 'pure' and civilized image of the Argentine identity were excluded from urban centers. It is in the suburbs that marginalized groups began to dance and play music. Tango is often referred to as the music of the immigrants to Argentina. For this reason, at the beginning of its history, tango was looked down upon by the Argentine elites. But as the dance and music became popular overseas, Argentine high society adopted the previously low-class dance form as their own, with some modifications.");