INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                                                                               Text) 
VALUES ('en_US',  'LOC_TREE_NYGUITA_ARGENTINA_NAME', 'Argentinian Civics'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_NAME', 'Congress of Tucumán'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_NAME', 'Civilization and Barbarism'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_NAME', 'Tango and Poetry'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_QUOTE', 'The soldiers of our land know no luxury, but glory.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_AUTHOR', 'José de San Martín'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_QUOTE', 'One does not renounce such an immense future, such a lofty mission, because of an accumulation of contradictions and difficulties. Difficulties are overcome: contradictions are overcome by contradicting them.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_AUTHOR', 'Domingo Faustino Sarmiento'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_QUOTE', 'A writer — and, I believe, generally all persons — must think that whatever happens to him or her is a resource. All things have been given to us for a purpose, and an artist must feel this more intensely.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_AUTHOR', 'Jorge Luis Borges'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_QUOTE_2', 'To govern is to populate.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_AUTHOR_2', 'Juan Bautista Alberdi'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_QUOTE_2', 'We shall seal with our blood and our swords, once and for ever, this Argentine nationality, which must develop like the Egyptian Pyramids and the power of Empires at the price of the blood and sweat of many generations.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_AUTHOR_2', 'Julio Argentino Roca'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_QUOTE_2', 'Let us admit, in any case, that among us now — if mostly still hidden — are many or all of the seeds of our future art, and not in museums overseas, and not in the homes of famous foreign dealers. Let us honor the rare ones, our rebellious spirits who, like this artist, before denying others, find affirmation in themselves; that instead of destroying, seek to build. Let us honor those who struggle so that the soul of our country can be more beautiful.'),
       ('en_US',  'LOC_CIVIC_NYGUITA_TANGO_AND_POETRY_AUTHOR_2', 'Xul Solar');

INSERT INTO LocalizedText
        (Tag, Language, Text)
VALUES  ('LOC_MOD_NYGUITA_GREAT_EUROPEAN_MIGRATION_WAVE_DESCRIPTION',	'en_US', '+15% [icon:GROWTH_RATE] [TIP:LOC_PEDIA_CONCEPTS_GROWTH_RATE_TOOLTIP]Growth Rate[/TIP] in all [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlements[/TIP].'),
        ('LOC_MOD_NYGUITA_VASTNESS_OF_THE_PAMPAS_DESCRIPTION', 		'en_US', '+1 [icon:SETTLEMENT_LIMIT] [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_LIMIT_TOOLTIP]Settlement Limit[/TIP].'),
        ('LOC_MOD_NYGUITA_LIGA_DE_GOBERNADORES_DESCRIPTION',		'en_US', '+5 [icon:YIELD_GOLD] Gold for every [icon:TRADITION] [TIP:LOC_PEDIA_CONCEPTS_TRADITION_TOOLTIP]Tradition[/TIP] in the [icon:GOVERNMENT] Government.'),
        ('LOC_MOD_NYGUITA_PATRIA_GRANDE_DESCRIPTION',			'en_US','+1 [icon:SETTLEMENT_LIMIT] [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_LIMIT_TOOLTIP]Settlement Limit[/TIP].'),
  	('LOC_MOD_NYGUITA_FLORIDA_AND_BOEDO_DESCRIPTION',		'en_US','+5 [icon:YIELD_CULTURE] Culture for each [icon:SOCIAL_POLICY] [TIP:LOC_PEDIA_CONCEPTS_SOCIAL_POLICY_TOOLTIP]Social Policy[/TIP], but not [icon:TRADITION] [TIP:LOC_PEDIA_CONCEPTS_TRADITION_TOOLTIP]Tradition[/TIP], slotted in the [icon:GOVERNMENT] Government.'),
  	('LOC_MOD_NYGUITA_GIANTS_OF_PATAGONIA_DESCRIPTION',		'en_US','+30% [icon:YIELD_PRODUCTION] Production towards Archeologists. +3 [icon:YIELD_SCIENCE] Science on [icon:NAR_REW_GREATWORK] [TIP:LOC_PEDIA_CONCEPTS_ARTIFACT_TOOLTIP]Artifacts[/TIP].'),
  	('LOC_MOD_NYGUITA_GAUCHESCO_DESCRIPTION',		        'en_US','+3 [icon:YIELD_CULTURE] Culture on Farms if a [icon:UNIT_NYGUITA_GAUCHO] Gaucho is on it.'),
  	('LOC_MOD_NYGUITA_PAYADOR_DESCRIPTION',		                'en_US','+3 [icon:YIELD_HAPPINESS] Happiness on Farms if a [icon:UNIT_NYGUITA_GAUCHO] Gaucho is on it.');

INSERT OR IGNORE INTO LocalizedText 
       	(Language, Tag,                                       Text) 
VALUES 	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_CONGRESS_OF_TUCUMAN_CHAPTER_HISTORY_PARA_1',  'The Congress of Tucuman was the representative assembly, initially meeting in San Miguel de Tucumán, that declared the independence of the United Provinces of South America on July 9, 1816, from the Spanish Empire. Delegate deputies, each representing 15,000 inhabitants, were sent from all the provinces to the sessions that started on March 24, 1816. After the declaration of independence, subsequent discussions centred on the form of government that the young state should have and were the Congress and the executive power should reside. The Congress was dissolved in 1820 after the Federal League Provinces of Santa Fe and Entre Ríos defeated a diminished Directorship army at the Battle of Cepeda.'),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_CIVILIZATION_AND_BARBARISM_CHAPTER_HISTORY_PARA_1',  "Facundo: Civilization and Barbarism is a book written in 1845 by Domingo Faustino Sarmiento, a writer and journalist who would become the second President of the Argentine Republic between 1868 and 1874. It defines the conditions the development of the region, as well as money, power and culture. The dichotomy between civilization and barbarism is the book's central idea; Facundo Quiroga is portrayed as wild, untamed, and standing opposed to true progress through his rejection of European cultural ideals. The conflict between civilization and barbarism mirrors Latin America's difficulties in the post-Independence era."),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_TANGO_AND_POETRY_CHAPTER_HISTORY_PARA_1',  "Argentina has a detailed literary history, as well as one of the region's most active publishing industries. Argentine writers have figured prominently in Latin American literature, since becoming a fully united entity in the 1850s, with a strong constitution and a defined nation-building plan. The struggle between the Federalists and the Unitarians, set the tone for Argentine literature of the time. With the many waves of immigrations, multiple influences rose up. After adopting French romanticism as a model with the Literatura Gauchesca, it was followed by the modernist and vanguardism movement with figures like Ricardo Güiraldes, Roberto Arlt and Victoria Ocampo."),
	('en_US',  'LOC_PEDIA_PAGE_CIVIC_NYGUITA_TANGO_AND_POETRY_CHAPTER_HISTORY_PARA_2',  "But those immigration waves also brought social tensions and conflicts. Under the Argentine government's efforts to Europeanize and modernize the country, those who did not fit the 'pure' and civilized image of the Argentine identity were excluded from urban centers. It is in the suburbs that marginalized groups began to dance and play music. Tango is often referred to as the music of the immigrants to Argentina. For this reason, at the beginning of its history, tango was looked down upon by the Argentine elites. But as the dance and music became popular overseas, Argentine high society adopted the previously low-class dance form as their own, with some modifications.");