INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                             Text) 
VALUES ('en_US',  'LOC_WONDER_NYGUITA_PALACIO_BAROLO_NAME', 'Palacio Barolo'),
       ('en_US',  'LOC_WONDER_NYGUITA_PALACIO_BAROLO_DESCRIPTION', '+5 [icon:YIELD_GOLD] Gold. +3 [icon:YIELD_CULTURE] Culture and [icon:YIELD_Gold] Gold on [icon:WONDER] [TIP:LOC_PEDIA_CONCEPTS_WONDERS_TOOLTIP]Wonders[/TIP]. Ageless. Must be placed adjacent to a [TIP:LOC_PEDIA_CONCEPTS_DISTRICT_TOOLTIP]District[/TIP].'),
       ('en_US',  'LOC_WONDER_NYGUITA_PALACIO_BAROLO_TOOLTIP', '+3 [icon:YIELD_CULTURE] Culture and [icon:YIELD_Gold] Gold on [icon:WONDER] [TIP:LOC_PEDIA_CONCEPTS_WONDERS_TOOLTIP]Wonders[/TIP]. [TIP:LOC_PEDIA_CONCEPTS_AGELESS_TOOLTIP]Ageless[/TIP]. Must be placed adjacent to a [TIP:LOC_PEDIA_CONCEPTS_DISTRICT_TOOLTIP]District[/TIP].'),
       ('en_US',  'LOC_WONDER_NYGUITA_PALACIO_BAROLO_QUOTE', 'Like the lark that soars in the air, first singing, then silent, content with the last sweetness that satiates it, such seemed to me that image, the imprint of the Eternal Pleasure.'),
       ('en_US',  'LOC_WONDER_NYGUITA_PALACIO_BAROLO_AUTHOR', 'Dante Alighieri');

INSERT OR IGNORE INTO LocalizedText 
       (Language, Tag,                                       Text) 
VALUES ('en_US',  'LOC_PEDIA_PAGE_WONDER_NYGUITA_PALACIO_BAROLO_CHAPTER_HISTORY_PARA_1',  "Palacio Barolo is a landmark office building, located in Buenos Aires, Argentina. It stood as Buenos Aires' tallest building for more than a decade. Italian architect Mario Palanti was commissioned to design the building by entrepreneur Luis Barolo, an Italian immigrant who had arrived in Argentina in 1890 and had made a fortune in knitted fabrics. The Palacio Barolo was designed in accordance with the cosmology of Dante's Divine Comedy, motivated by the architect's admiration for Alighieri. There are 22 floors, divided into three sections. The basement and ground floor represent hell, floors 1-14 are purgatory, and 15-22 represent heaven. The building is 100 meters (330 feet) tall, one meter for each canto of the Divine Comedy. The lighthouse at the top of the building can be seen all the way in Montevideo, Uruguay. The owner planned to use only 3 floors, and to rent the rest.");